//AUTH
//LOGIN
export const LOGIN = 'LOGIN'
//REGISTER
export const REGISTER = 'REGISTER'

//ROOMS
//GET ROOMS
export const GET_ROOMS = 'GET_ROOMS'
//ADD ROOMS
export const ADD_ROOMS = 'ADD_ROOMS'
//EDIT ROOMS
export const EDIT_ROOMS = 'EDIT_ROOMS'
//DELETE ROOMS
export const DELETE_ROOMS = 'DELETE_ROOMS'

//CUSTOMER
//GET CUSTOMER
export const GET_CUSTOMER = 'GET_CUSTOMER'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
export const UPLOAD_IMAGE_CUSTOMER = 'UPLOAD_IMAGE_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'

//CHECKIN
//GET CHECKIN
export const GET_CHECKIN = 'GET_CHECKIN'
export const ADD_CHECKIN = 'ADD_CHECKIN'
export const CHECKOUT = 'CHECKOUT'

